### ISSUE TITLE
can this be used for chroot not proot?

### ISSUE THREAD

**Issue by dhuux** [dianqk/nix-on-termux-bootstrap#1]
there are people who did this on Termux but they never explain how to do it for beginners.

[check this. if you have a rooted phone this could work. but i got mounting error and i don't have the knowledge to make it work. ](https://github.com/noamraph/nixsa)

thanks.

**Comment by dianqk** [comment]
I haven't tried that, I would recommend using Debian to bootstrap nix.

**Comment by dhuux** [comment]
i tried in chroot Achlinux and its working but i hoped it would work in termux environement.

**Comment by dhuux** [comment]
thanks.
